"""
Card name generation, split by naming style to match how Magic actually
names creatures:

- Ordinary creatures are named after their species/role ("Grizzly Bears",
  "Goblin Piker") -- generated by recombining real name words with a
  word-level Markov chain, so the result is always assembled from actual
  English words pulled from real cards, never invented syllables.
- Legendary creatures get personal character names ("Jace", "Chandra, Fire
  Artisan") -- the given name from a character-level Markov chain, free to
  invent new syllables since that's exactly how invented character names are
  supposed to sound (see momir/markov.py's CharMarkovChain); the epithet
  after the comma ("Fire Artisan", "the Mind Sculptor"), when there is one,
  is instead a real English phrase, so it's generated the same word-level way
  as an ordinary creature's name -- recombining real epithet words rather
  than inventing new ones.

How often a generated card gets a character name mirrors how often real
creatures are legendary, so this doesn't have to hand-tune a probability
that'll drift out of sync with the corpus.
"""
from __future__ import annotations

import random
from dataclasses import dataclass

from .corpus import Corpus
from .markov import CharMarkovChain, WordMarkovChain

CHARACTER_NAME_MARKOV_ORDER = 3
# Deliberately low: a higher order would mostly just reproduce whole real
# names verbatim. Order 2 still lets "Grizzly" from one real name combine
# with "Piker" from another, while keeping short, real (adjective, noun)
# pairings coherent.
COMMON_NAME_WORD_ORDER = 2
MAX_COMMON_NAME_WORDS = 4
COMMON_NAME_ATTEMPTS = 25

# Words a generated common name shouldn't dangle on, mirroring
# CharMarkovChain.generate_title's dangling-stopword retry -- a word chain
# stopping early on "of"/"the" reads as obviously cut off ("Kami of the").
_DANGLING_STOPWORDS = {"of", "the", "and", "an", "a", "in", "on", "to"}


@dataclass
class NameChains:
    character: CharMarkovChain
    common: WordMarkovChain
    epithet: WordMarkovChain
    # Share of generated names that should use the character chain, set to
    # match the real corpus's legendary/non-legendary split.
    character_chance: float
    # Share of legendary names that carry a ", Epithet" (vs. a bare given
    # name like "Jace"), set to match the real corpus's own split.
    epithet_chance: float


def build_name_chains(corpus: Corpus) -> NameChains:
    given_names: list[str] = []
    epithets: list[str] = []
    for name in corpus.character_names:
        given, sep, epithet = name.partition(",")
        given_names.append(given.strip())
        if sep:
            epithets.append(epithet.strip())

    character = CharMarkovChain(order=CHARACTER_NAME_MARKOV_ORDER)
    character.train(given_names)

    common = WordMarkovChain(order=COMMON_NAME_WORD_ORDER)
    epithet_chain = WordMarkovChain(order=COMMON_NAME_WORD_ORDER)
    # WordMarkovChain trains on (sentence, position, shape) triples; names
    # don't have a construct "shape" the way rules text does, so every name
    # gets the same constant tag -- shape-splitting is a no-op here.
    common.train([(name, 0, "name") for name in corpus.common_names])
    epithet_chain.train([(epithet, 0, "epithet") for epithet in epithets])

    total = len(corpus.character_names) + len(corpus.common_names)
    character_chance = (len(corpus.character_names) / total) if total else 0.0
    epithet_chance = (len(epithets) / len(given_names)) if given_names else 0.0
    return NameChains(
        character=character,
        common=common,
        epithet=epithet_chain,
        character_chance=character_chance,
        epithet_chance=epithet_chance,
    )


def _generate_words(chain: WordMarkovChain, rng: random.Random, max_words: int) -> str:
    """Generate from a word-level chain, retrying until the result doesn't
    dangle mid-phrase on a stopword (e.g. "... of the") -- shared by common
    names and epithets, which have the same failure mode."""
    best = ""
    for _ in range(COMMON_NAME_ATTEMPTS):
        candidate = chain.generate(max_words=max_words, rng=rng)
        if not candidate:
            continue
        last_word = candidate.rsplit(" ", 1)[-1].lower()
        if last_word not in _DANGLING_STOPWORDS:
            return candidate
        if len(candidate) > len(best):
            best = candidate
    return best


def generate_name(chains: NameChains, rng: random.Random | None = None) -> str:
    rng = rng or random
    if rng.random() >= chains.character_chance:
        name = _generate_words(chains.common, rng, MAX_COMMON_NAME_WORDS)
        if name:
            return name
    # Also the fallback when the common chain has nothing trained, or every
    # attempt above came up empty/dangling.
    given = chains.character.generate_title(rng=rng)
    if rng.random() < chains.epithet_chance:
        epithet = _generate_words(chains.epithet, rng, MAX_COMMON_NAME_WORDS)
        if epithet:
            return f"{given}, {epithet}"
    return given
