"""
Card name generation, split by naming style to match how Magic actually
names creatures:

- Ordinary creatures are named after their species/role ("Grizzly Bears",
  "Goblin Piker") -- generated by recombining real name words with a
  word-level Markov chain, so the result is always assembled from actual
  English words pulled from real cards, never invented syllables.
- Legendary creatures get personal character names ("Jace", "Chandra, Fire
  Artisan") -- generated by a character-level Markov chain, which is free to
  invent new syllables since that's exactly how invented character names are
  supposed to sound (see momir/markov.py's CharMarkovChain).

How often a generated card gets a character name mirrors how often real
creatures are legendary, so this doesn't have to hand-tune a probability
that'll drift out of sync with the corpus.
"""
from __future__ import annotations

import random
from dataclasses import dataclass

from .corpus import Corpus
from .markov import CharMarkovChain, WordMarkovChain

CHARACTER_NAME_MARKOV_ORDER = 3
# Deliberately low: a higher order would mostly just reproduce whole real
# names verbatim. Order 2 still lets "Grizzly" from one real name combine
# with "Piker" from another, while keeping short, real (adjective, noun)
# pairings coherent.
COMMON_NAME_WORD_ORDER = 2
MAX_COMMON_NAME_WORDS = 4
COMMON_NAME_ATTEMPTS = 25

# Words a generated common name shouldn't dangle on, mirroring
# CharMarkovChain.generate_title's dangling-stopword retry -- a word chain
# stopping early on "of"/"the" reads as obviously cut off ("Kami of the").
_DANGLING_STOPWORDS = {"of", "the", "and", "an", "a", "in", "on", "to"}


@dataclass
class NameChains:
    character: CharMarkovChain
    common: WordMarkovChain
    # Share of generated names that should use the character chain, set to
    # match the real corpus's legendary/non-legendary split.
    character_chance: float


def build_name_chains(corpus: Corpus) -> NameChains:
    character = CharMarkovChain(order=CHARACTER_NAME_MARKOV_ORDER)
    character.train(corpus.character_names)

    common = WordMarkovChain(order=COMMON_NAME_WORD_ORDER)
    common.train([(name, 0) for name in corpus.common_names])

    total = len(corpus.character_names) + len(corpus.common_names)
    character_chance = (len(corpus.character_names) / total) if total else 0.0
    return NameChains(character=character, common=common, character_chance=character_chance)


def _generate_common_name(chains: NameChains, rng: random.Random) -> str:
    best = ""
    for _ in range(COMMON_NAME_ATTEMPTS):
        candidate = chains.common.generate(max_words=MAX_COMMON_NAME_WORDS, rng=rng)
        if not candidate:
            continue
        last_word = candidate.rsplit(" ", 1)[-1].lower()
        if last_word not in _DANGLING_STOPWORDS:
            return candidate
        if len(candidate) > len(best):
            best = candidate
    return best


def generate_name(chains: NameChains, rng: random.Random | None = None) -> str:
    rng = rng or random
    if rng.random() >= chains.character_chance:
        name = _generate_common_name(chains, rng)
        if name:
            return name
    # Also the fallback when the common chain has nothing trained, or every
    # attempt above came up empty/dangling.
    return chains.character.generate_title(rng=rng)
